### ISSUE TITLE
Virtual Computer or Local

### ISSUE THREAD

**Issue by monal20** [CMURoboTouch/tactile_optical_simulation#1]
Hello. I was just wondering for this project, if it would be better to install everything to a local machine or a virtual environment. If the former, I am on windows, and running into trouble installing mitsuba2. 

Specifically, this part:
source setpath_linux.sh

It gives me an "'source' is not recognized as an internal or external command,
operable program or batch file" error.

Thank you

**Comment by arpit15** [comment]
This is good issue for [mitsuba2-python-package](https://github.com/CMURoboTouch/mitsuba2-python-package) repo. The steps to activate mitsuba2 on windows are [here](https://github.com/CMURoboTouch/mitsuba2-python-package#windows). Its best to use virtual environments to control python version across projects. Please look into [anaconda](https://docs.anaconda.com/anaconda/install/windows/) for windows and [pyenv](https://github.com/pyenv/pyenv) for linux and mac. 
I am going to close this issue as it is not relevant to this project. Please open a new issue on mitsuba2-python-package repo, if there is a problem related to setting up mitsuba2.
