### ISSUE TITLE
Could not instantiate texture plugin of type "bitmap": 

### ISSUE THREAD

**Issue by rajk97** [CMURoboTouch/tactile_optical_simulation#3]
I'm getting the following error when trying to run the sample script of generate_image.py

`Traceback (most recent call last):
  File "new_mesh_render.py", line 41, in <module> scene = load_file(model_fn, **render_params, **params)

RuntimeError: \u200b[xml.cpp:1047] Error while loading "models/components/flat_elastomer_material.xml" (near line 6, col 8): could not instantiate texture plugin of type "bitmap": 

[xml.cpp:1047]   [FileStream] "textures/flatgel_surface_texture.png": I/O error while attempting to open file: No such file or directory
`

![image](https://user-images.githubusercontent.com/32988799/106977138-bbf96000-6727-11eb-83fa-d99d73b88e11.png)

Any idea how to resolve this? Thanks!

**Comment by arpit15** [comment]
This issue should be resolved in c71d4fd06d28ece021a9546114999363404c1a86. Feel free to open this issue if the problem persists.
